---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.6
  - 2.4.3
  - 2.5.0
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v 1.17.3

install:
  - bundle install --jobs=3 --retry=3

script: bundle exec rake spec
